name: Publish Docker image to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  push_to_dockerHub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Executando scripts appsettings
        run: |
              sed -i "s,#CONEXAO_BANCO_DADOS_PRODUCAO#,${{ secrets.CONEXAO_BANCO_DADOS_PRODUCAO }},g" src/Backend/MeuLivroDeReceitas.Api/appsettings.Production.json
              sed -i "s,#JWT_CHAVE_TOKEN#,${{ secrets.JWT_CHAVE_TOKEN }},g" src/Backend/MeuLivroDeReceitas.Api/appsettings.Production.json
              sed -i "s,#SENHA_CHAVE_ADICIONAL#,${{ secrets.SENHA_CHAVE_ADICIONAL }},g" src/Backend/MeuLivroDeReceitas.Api/appsettings.Production.json
              sed -i "s,#HASH_IDS_SALT#,${{ secrets.HASH_IDS_SALT }},g" src/Backend/MeuLivroDeReceitas.Api/appsettings.Production.json
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: welissonarley/meulivrodereceitas
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
